In [2]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import preprocessing

data = pd.read_csv('car.data')
data.head()

buying  maint doors persons lug_boot safety target
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [3]:
le = preprocessing.LabelEncoder()
buying = le.fit_transform(list(data["buying"]))
buying


array([3, 3, 3, ..., 1, 1, 1], dtype=int64)

In [10]:
maint = le.fit_transform(list(data["maint"]))
doors = le.fit_transform(list(data["doors"]))
persons = le.fit_transform(list(data["persons"]))
lug_boot = le.fit_transform(list(data["lug_boot"]))
safety = le.fit_transform(list(data["safety"]))
target = le.fit_transform(list(data["target"]))

# doors = list(data['doors'])
# doors = [int(door) for door in doors] # if just decimal values exists in string 


In [11]:

X = list(zip(buying, maint,doors, persons,lug_boot,safety))

In [12]:
X

[(3, 3, 0, 0, 2, 1),
 (3, 3, 0, 0, 2, 2),
 (3, 3, 0, 0, 2, 0),
 (3, 3, 0, 0, 1, 1),
 (3, 3, 0, 0, 1, 2),
 (3, 3, 0, 0, 1, 0),
 (3, 3, 0, 0, 0, 1),
 (3, 3, 0, 0, 0, 2),
 (3, 3, 0, 0, 0, 0),
 (3, 3, 0, 1, 2, 1),
 (3, 3, 0, 1, 2, 2),
 (3, 3, 0, 1, 2, 0),
 (3, 3, 0, 1, 1, 1),
 (3, 3, 0, 1, 1, 2),
 (3, 3, 0, 1, 1, 0),
 (3, 3, 0, 1, 0, 1),
 (3, 3, 0, 1, 0, 2),
 (3, 3, 0, 1, 0, 0),
 (3, 3, 0, 2, 2, 1),
 (3, 3, 0, 2, 2, 2),
 (3, 3, 0, 2, 2, 0),
 (3, 3, 0, 2, 1, 1),
 (3, 3, 0, 2, 1, 2),
 (3, 3, 0, 2, 1, 0),
 (3, 3, 0, 2, 0, 1),
 (3, 3, 0, 2, 0, 2),
 (3, 3, 0, 2, 0, 0),
 (3, 3, 1, 0, 2, 1),
 (3, 3, 1, 0, 2, 2),
 (3, 3, 1, 0, 2, 0),
 (3, 3, 1, 0, 1, 1),
 (3, 3, 1, 0, 1, 2),
 (3, 3, 1, 0, 1, 0),
 (3, 3, 1, 0, 0, 1),
 (3, 3, 1, 0, 0, 2),
 (3, 3, 1, 0, 0, 0),
 (3, 3, 1, 1, 2, 1),
 (3, 3, 1, 1, 2, 2),
 (3, 3, 1, 1, 2, 0),
 (3, 3, 1, 1, 1, 1),
 (3, 3, 1, 1, 1, 2),
 (3, 3, 1, 1, 1, 0),
 (3, 3, 1, 1, 0, 1),
 (3, 3, 1, 1, 0, 2),
 (3, 3, 1, 1, 0, 0),
 (3, 3, 1, 2, 2, 1),
 (3, 3, 1, 2, 2, 2),
 (3, 3, 1, 2,

In [13]:
y = list(target)
y

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [20]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X,y,test_size=0.1)

X_train

[(3, 1, 3, 2, 2, 2),
 (2, 0, 1, 1, 2, 0),
 (1, 1, 0, 0, 2, 2),
 (0, 1, 3, 0, 0, 2),
 (0, 2, 0, 1, 1, 1),
 (3, 3, 3, 1, 0, 2),
 (0, 0, 0, 1, 0, 1),
 (2, 2, 3, 2, 2, 1),
 (1, 3, 0, 2, 2, 1),
 (2, 3, 3, 2, 0, 2),
 (2, 2, 1, 1, 0, 0),
 (1, 0, 3, 0, 0, 1),
 (2, 3, 0, 2, 0, 0),
 (0, 2, 2, 0, 1, 1),
 (3, 2, 2, 1, 2, 0),
 (3, 2, 3, 2, 2, 2),
 (1, 2, 3, 1, 1, 0),
 (1, 3, 0, 1, 0, 2),
 (3, 0, 1, 0, 2, 0),
 (0, 1, 2, 1, 2, 2),
 (1, 3, 3, 1, 1, 0),
 (3, 1, 3, 1, 2, 0),
 (2, 0, 1, 2, 0, 0),
 (2, 0, 3, 1, 0, 1),
 (2, 1, 2, 2, 0, 2),
 (3, 0, 0, 1, 2, 0),
 (2, 3, 1, 1, 0, 0),
 (2, 3, 0, 0, 2, 0),
 (3, 3, 2, 1, 1, 0),
 (3, 3, 2, 0, 2, 0),
 (0, 1, 1, 2, 0, 2),
 (1, 0, 1, 1, 2, 0),
 (2, 2, 1, 1, 1, 0),
 (3, 2, 0, 1, 0, 0),
 (1, 1, 3, 1, 0, 2),
 (2, 3, 0, 1, 1, 1),
 (2, 2, 0, 2, 1, 0),
 (2, 1, 0, 2, 0, 1),
 (1, 0, 1, 0, 1, 1),
 (2, 2, 0, 1, 0, 0),
 (2, 0, 3, 0, 2, 2),
 (3, 2, 2, 0, 0, 2),
 (0, 3, 3, 0, 0, 1),
 (0, 2, 0, 0, 1, 1),
 (3, 0, 3, 1, 0, 1),
 (1, 2, 2, 1, 1, 2),
 (1, 2, 3, 1, 0, 0),
 (3, 1, 1, 1,

In [31]:
model = KNeighborsClassifier(n_neighbors=7)
model.fit(X_train,y_train)
accuracy = model.score(X_test, y_test)
accuracy

0.9248554913294798

In [36]:
predicted = model.predict(X_test)
predicted
X_test




[(0, 0, 0, 0, 1, 1),
 (2, 1, 3, 2, 2, 1),
 (1, 3, 0, 2, 1, 0),
 (2, 2, 3, 0, 1, 1),
 (2, 3, 2, 1, 2, 1),
 (0, 0, 3, 1, 2, 2),
 (3, 0, 0, 2, 2, 1),
 (2, 3, 1, 2, 2, 2),
 (3, 0, 1, 2, 2, 1),
 (0, 1, 3, 0, 0, 0),
 (0, 0, 0, 2, 1, 0),
 (3, 2, 0, 0, 2, 0),
 (3, 3, 1, 0, 0, 2),
 (3, 1, 3, 2, 0, 0),
 (3, 1, 1, 1, 0, 2),
 (3, 3, 0, 2, 1, 2),
 (3, 0, 2, 1, 0, 0),
 (3, 2, 1, 0, 0, 2),
 (1, 1, 2, 2, 1, 2),
 (2, 2, 1, 2, 2, 2),
 (2, 3, 0, 2, 2, 0),
 (2, 0, 2, 0, 0, 2),
 (0, 2, 0, 2, 1, 2),
 (3, 1, 0, 2, 2, 2),
 (0, 2, 3, 2, 0, 1),
 (2, 3, 2, 2, 1, 0),
 (1, 2, 0, 0, 1, 0),
 (1, 2, 0, 0, 0, 2),
 (2, 3, 1, 2, 0, 1),
 (0, 1, 2, 0, 1, 0),
 (3, 3, 1, 0, 1, 1),
 (3, 0, 1, 0, 0, 2),
 (2, 1, 3, 1, 2, 0),
 (3, 1, 1, 2, 1, 2),
 (3, 2, 2, 0, 0, 0),
 (0, 3, 2, 0, 2, 2),
 (0, 1, 1, 1, 2, 2),
 (0, 1, 0, 1, 2, 2),
 (1, 1, 3, 0, 0, 2),
 (3, 0, 0, 0, 0, 0),
 (0, 2, 2, 2, 1, 0),
 (2, 2, 1, 2, 1, 0),
 (0, 0, 1, 1, 2, 0),
 (1, 0, 0, 1, 0, 0),
 (2, 2, 2, 0, 1, 2),
 (2, 1, 2, 1, 0, 1),
 (3, 2, 3, 1, 2, 0),
 (1, 1, 1, 1,

In [37]:
names = ['unacc', 'acc', 'good', 'vgood']
for x in range(len(predicted)):
    print("Predicted: ",names[predicted[x]], "Data:", X_test[x], "Actual class: ", names[y_test[x]])
    n = model.kneighbors([X_test[x]], 9, True)
    print(n[0])
    

Predicted:  good Data: (0, 0, 0, 0, 1, 1) Actual class:  good
[[1.         1.         1.         1.         1.         1.
  1.         1.41421356 1.41421356]]
Predicted:  good Data: (2, 1, 3, 2, 2, 1) Actual class:  good
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Predicted:  unacc Data: (1, 3, 0, 2, 1, 0) Actual class:  unacc
[[1.         1.         1.         1.         1.         1.
  1.         1.         1.41421356]]
Predicted:  good Data: (2, 2, 3, 0, 1, 1) Actual class:  good
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Predicted:  good Data: (2, 3, 2, 1, 2, 1) Actual class:  good
[[1.         1.         1.         1.         1.         1.
  1.         1.         1.41421356]]
Predicted:  good Data: (0, 0, 3, 1, 2, 2) Actual class:  good
[[1.         1.         1.         1.         1.         1.
  1.         1.41421356 1.41421356]]
Predicted:  good Data: (3, 0, 0, 2, 2, 1) Actual class:  good
[[1.         1.         1.         1.         1.         1.41421356
  1.41421356 1.41421356 1.41421356]]
Predicted