# Feature Extraction from text data

## TF-IDF

### Tf = number of occurance of a term in one document / total numbers of terms

### idf = log(N/n) N = documents counts , n = count of docs which has specofic term

### tf-idf value = Tf * idf

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
text = ["hello, my name is sadeghi data and i am a data scientist"]
text1 = ["You are watching data science course. scientist"]

In [19]:
vectorizer = CountVectorizer()

In [31]:
x= vectorizer.fit_transform(text)
x.toarray()

array([[1, 1, 2, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [21]:
vectorizer.vocabulary_

{'hello': 3,
 'my': 5,
 'name': 6,
 'is': 4,
 'sadeghi': 7,
 'data': 2,
 'and': 1,
 'am': 0,
 'scientist': 8}

In [22]:
newvector = vectorizer.transform(text1)

In [32]:
newvector.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
text = ["hello, my name is sadeghi data and i am a data scientist", "this is data science","data science is good way to analys data"] 

In [57]:
vectorizer.fit(text)

CountVectorizer()

In [58]:
vectorizer.vocabulary_

{'hello': 5,
 'my': 7,
 'name': 8,
 'is': 6,
 'sadeghi': 9,
 'data': 3,
 'and': 2,
 'am': 0,
 'scientist': 11,
 'this': 12,
 'science': 10,
 'good': 4,
 'way': 14,
 'to': 13,
 'analys': 1}

In [59]:
text_as_input = text[0]

In [60]:
text_as_input

'hello, my name is sadeghi data and i am a data scientist'

In [61]:
vector = vectorizer.transform([text_as_input])

In [65]:

vector.toarray()

array([[1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [66]:
import numpy as np

In [67]:
a1 = np.array([1,2,3])

In [68]:
type(a1)

numpy.ndarray

In [71]:
a2 = np.array([[1,2,3],[4,5,6]])

In [72]:
type(a2)

numpy.ndarray

In [73]:
a1.shape

(2, 3)

In [74]:
a1.ndim

2

In [75]:
a1.dtype

dtype('int32')

In [76]:
a1.size

6

In [77]:
import pandas as pd

In [78]:
df = pd.DataFrame(a1)
df

0  1  2
0  1  2  3
1  4  5  6

In [79]:
ones= np.ones((2,3))

In [80]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
zeros= np.zeros((2,3))

In [82]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
range_array = np.arange(0,10,2)

In [84]:
range_array

array([0, 2, 4, 6, 8])

In [86]:
np.random.random((5,3))

array([[0.8259489 , 0.66454167, 0.56888087],
       [0.28761404, 0.30073096, 0.11272856],
       [0.88760367, 0.34961011, 0.55987561],
       [0.27444401, 0.51097281, 0.84715322],
       [0.39416116, 0.86698376, 0.40757171]])

In [89]:
np.random.seed(30)

In [92]:
n_ar = np.random.random((5,3))

In [93]:
np.unique(n_ar)

array([0.02662436, 0.03113075, 0.08970338, 0.19577126, 0.2351805 ,
       0.23898637, 0.28643533, 0.37642024, 0.49414912, 0.55561256,
       0.62909983, 0.68834438, 0.73495258, 0.90251384, 0.99419368])